/* GENERATED FILE - regenerate via util/genmconveys.c.
   Do not hand-edit. */
#ifndef MCONVEYS_H
#define MCONVEYS_H

struct mconveys_entry {
    const char *name;   /* matches mons[].mname, lowercase */
    const char *text;   /* what eating this corpse does */
};

static const struct mconveys_entry mconveys_table[] = {
    { "giant ant", "none" },
    { "killer bee", "may confer poison resistance; poisonous to eat" },
    { "soldier ant", "may confer poison resistance; poisonous to eat" },
    { "fire ant", "may confer fire resistance" },
    { "giant beetle", "may confer poison resistance; poisonous to eat" },
    { "queen bee", "may confer poison resistance; poisonous to eat" },
    { "acid blob", "acidic to eat; cures stoning if eaten while petrifying" },
    { "quivering blob", "may confer poison resistance" },
    { "gelatinous cube", "may confer fire resistance, cold resistance, sleep resistance, shock resistance; acidic to eat; cures stoning if eaten while petrifying" },
    { "chickatrice", "instant stoning unless stoning-resistant; may confer poison resistance" },
    { "cockatrice", "instant stoning unless stoning-resistant; may confer poison resistance" },
    { "pyrolisk", "may confer fire resistance, poison resistance" },
    { "jackal", "none" },
    { "fox", "none" },
    { "coyote", "none" },
    { "werejackal", "poisonous to eat" },
    { "little dog", "none" },
    { "dingo", "none" },
    { "dog", "none" },
    { "large dog", "none" },
    { "wolf", "none" },
    { "werewolf", "poisonous to eat" },
    { "winter wolf cub", "may confer cold resistance" },
    { "warg", "none" },
    { "winter wolf", "may confer cold resistance" },
    { "hell hound pup", "may confer fire resistance" },
    { "hell hound", "may confer fire resistance" },
    { "gas spore", "none" },
    { "floating eye", "may confer telepathy" },
    { "freezing sphere", "may confer cold resistance" },
    { "flaming sphere", "may confer fire resistance" },
    { "shocking sphere", "may confer shock resistance" },
    { "kitten", "none" },
    { "housecat", "none" },
    { "jaguar", "none" },
    { "lynx", "none" },
    { "panther", "none" },
    { "large cat", "none" },
    { "tiger", "none" },
    { "gremlin", "may confer poison resistance; poisonous to eat" },
    { "gargoyle", "none" },
    { "winged gargoyle", "none" },
    { "hobbit", "none" },
    { "dwarf", "counts as cannibalism for Dwarven characters" },
    { "bugbear", "none" },
    { "dwarf lord", "counts as cannibalism for Dwarven characters" },
    { "dwarf king", "counts as cannibalism for Dwarven characters" },
    { "mind flayer", "may confer telepathy; may raise Intelligence (otherwise as telepathy)" },
    { "master mind flayer", "may confer telepathy; may raise Intelligence (otherwise as telepathy)" },
    { "manes", "poisonous to eat" },
    { "homunculus", "may confer sleep resistance, poison resistance; poisonous to eat" },
    { "imp", "none" },
    { "lemure", "may confer sleep resistance; poisonous to eat" },
    { "quasit", "may confer poison resistance" },
    { "tengu", "may confer poison resistance; may confer teleportitis; may confer teleport control" },
    { "blue jelly", "may confer cold resistance, poison resistance" },
    { "spotted jelly", "acidic to eat; cures stoning if eaten while petrifying" },
    { "ochre jelly", "acidic to eat; cures stoning if eaten while petrifying" },
    { "kobold", "poisonous to eat" },
    { "large kobold", "poisonous to eat" },
    { "kobold lord", "poisonous to eat" },
    { "kobold shaman", "poisonous to eat" },
    { "leprechaun", "may confer teleportitis" },
    { "small mimic", "risk of turning into a mimic" },
    { "large mimic", "risk of turning into a mimic" },
    { "giant mimic", "risk of turning into a mimic" },
    { "wood nymph", "may confer teleportitis" },
    { "water nymph", "may confer teleportitis" },
    { "mountain nymph", "may confer teleportitis" },
    { "goblin", "counts as cannibalism for Orcish characters" },
    { "hobgoblin", "counts as cannibalism for Orcish characters" },
    { "orc", "counts as cannibalism for Orcish characters" },
    { "hill orc", "counts as cannibalism for Orcish characters" },
    { "mordor orc", "counts as cannibalism for Orcish characters" },
    { "uruk-hai", "counts as cannibalism for Orcish characters" },
    { "orc shaman", "counts as cannibalism for Orcish characters" },
    { "orc-captain", "counts as cannibalism for Orcish characters" },
    { "rock piercer", "none" },
    { "iron piercer", "none" },
    { "glass piercer", "none" },
    { "rothe", "none" },
    { "mumak", "none" },
    { "leocrotta", "none" },
    { "wumpus", "none" },
    { "titanothere", "none" },
    { "baluchitherium", "none" },
    { "mastodon", "none" },
    { "sewer rat", "none" },
    { "giant rat", "none" },
    { "rabid rat", "poisonous to eat" },
    { "wererat", "poisonous to eat" },
    { "rock mole", "none" },
    { "woodchuck", "none" },
    { "cave spider", "may confer poison resistance" },
    { "centipede", "may confer poison resistance" },
    { "giant spider", "may confer poison resistance; poisonous to eat" },
    { "scorpion", "may confer poison resistance; poisonous to eat" },
    { "lurker above", "none" },
    { "trapper", "none" },
    { "pony", "none" },
    { "white unicorn", "may confer poison resistance" },
    { "gray unicorn", "may confer poison resistance" },
    { "black unicorn", "may confer poison resistance" },
    { "horse", "none" },
    { "warhorse", "none" },
    { "fog cloud", "none" },
    { "dust vortex", "none" },
    { "ice vortex", "none" },
    { "energy vortex", "none" },
    { "steam vortex", "none" },
    { "fire vortex", "none" },
    { "baby long worm", "none" },
    { "baby purple worm", "none" },
    { "long worm", "none" },
    { "purple worm", "none" },
    { "grid bug", "none" },
    { "xan", "may confer poison resistance; poisonous to eat" },
    { "yellow light", "causes stunning" },
    { "black light", "causes hallucination" },
    { "zruty", "none" },
    { "couatl", "poisonous to eat" },
    { "aleax", "none" },
    { "angel", "none" },
    { "ki-rin", "none" },
    { "archon", "none" },
    { "bat", "causes stunning" },
    { "giant bat", "causes stunning" },
    { "raven", "none" },
    { "vampire bat", "poisonous to eat" },
    { "plains centaur", "none" },
    { "forest centaur", "none" },
    { "mountain centaur", "none" },
    { "baby gray dragon", "none" },
    { "baby silver dragon", "none" },
    { "baby red dragon", "none" },
    { "baby white dragon", "none" },
    { "baby orange dragon", "none" },
    { "baby black dragon", "none" },
    { "baby blue dragon", "none" },
    { "baby green dragon", "poisonous to eat" },
    { "baby yellow dragon", "acidic to eat; cures stoning if eaten while petrifying" },
    { "gray dragon", "none" },
    { "silver dragon", "none" },
    { "red dragon", "may confer fire resistance" },
    { "white dragon", "may confer cold resistance" },
    { "orange dragon", "may confer sleep resistance" },
    { "black dragon", "may confer disintegration resistance" },
    { "blue dragon", "may confer shock resistance" },
    { "green dragon", "may confer poison resistance; poisonous to eat" },
    { "yellow dragon", "acidic to eat; cures stoning if eaten while petrifying" },
    { "stalker", "grants temporary invisibility (permanent invisibility and see invisible if already invisible); causes stunning" },
    { "air elemental", "none" },
    { "fire elemental", "none" },
    { "earth elemental", "none" },
    { "water elemental", "none" },
    { "lichen", "never rots" },
    { "brown mold", "may confer cold resistance, poison resistance" },
    { "yellow mold", "may confer poison resistance; poisonous to eat; causes hallucination" },
    { "green mold", "acidic to eat; cures stoning if eaten while petrifying" },
    { "red mold", "may confer fire resistance, poison resistance" },
    { "shrieker", "may confer poison resistance" },
    { "violet fungus", "may confer poison resistance; causes hallucination" },
    { "gnome", "counts as cannibalism for Gnomish characters" },
    { "gnome lord", "counts as cannibalism for Gnomish characters" },
    { "gnomish wizard", "counts as cannibalism for Gnomish characters" },
    { "gnome king", "counts as cannibalism for Gnomish characters" },
    { "giant", "may confer strength gain" },
    { "stone giant", "may confer strength gain" },
    { "hill giant", "may confer strength gain" },
    { "fire giant", "may confer fire resistance; may confer strength gain" },
    { "frost giant", "may confer cold resistance; may confer strength gain" },
    { "ettin", "none" },
    { "storm giant", "may confer shock resistance; may confer strength gain" },
    { "titan", "none" },
    { "minotaur", "none" },
    { "jabberwock", "none" },
    { "keystone kop", "counts as cannibalism for Human characters" },
    { "kop sergeant", "counts as cannibalism for Human characters" },
    { "kop lieutenant", "counts as cannibalism for Human characters" },
    { "kop kaptain", "counts as cannibalism for Human characters" },
    { "lich", "may confer cold resistance; poisonous to eat" },
    { "demilich", "may confer cold resistance; poisonous to eat" },
    { "master lich", "may confer fire resistance, cold resistance; poisonous to eat" },
    { "arch-lich", "may confer fire resistance, cold resistance; poisonous to eat" },
    { "kobold mummy", "poisonous to eat" },
    { "gnome mummy", "poisonous to eat; counts as cannibalism for Gnomish characters" },
    { "orc mummy", "poisonous to eat; counts as cannibalism for Orcish characters" },
    { "dwarf mummy", "poisonous to eat; counts as cannibalism for Dwarven characters" },
    { "elf mummy", "poisonous to eat; counts as cannibalism for Elven characters" },
    { "human mummy", "poisonous to eat" },
    { "ettin mummy", "poisonous to eat" },
    { "giant mummy", "may confer strength gain; poisonous to eat" },
    { "red naga hatchling", "may confer fire resistance, poison resistance" },
    { "black naga hatchling", "may confer poison resistance; acidic to eat; cures stoning if eaten while petrifying" },
    { "golden naga hatchling", "may confer poison resistance" },
    { "guardian naga hatchling", "may confer poison resistance" },
    { "red naga", "may confer fire resistance, poison resistance" },
    { "black naga", "may confer poison resistance; acidic to eat; cures stoning if eaten while petrifying" },
    { "golden naga", "may confer poison resistance" },
    { "guardian naga", "may confer poison resistance; poisonous to eat" },
    { "ogre", "none" },
    { "ogre lord", "none" },
    { "ogre king", "none" },
    { "gray ooze", "may confer fire resistance, cold resistance, poison resistance; acidic to eat; cures stoning if eaten while petrifying" },
    { "brown pudding", "may confer cold resistance, shock resistance, poison resistance; acidic to eat; cures stoning if eaten while petrifying" },
    { "green slime", "turns you into green slime unless slime-proof; poisonous to eat; acidic to eat; cures stoning if eaten while petrifying" },
    { "black pudding", "may confer cold resistance, shock resistance, poison resistance; acidic to eat; cures stoning if eaten while petrifying" },
    { "quantum mechanic", "may confer teleportitis; randomly toggles intrinsic speed (faster or slower); poisonous to eat" },
    { "rust monster", "none" },
    { "disenchanter", "risk of an attribute curse" },
    { "garter snake", "none" },
    { "snake", "may confer poison resistance; poisonous to eat" },
    { "water moccasin", "may confer poison resistance; poisonous to eat" },
    { "python", "none" },
    { "pit viper", "may confer poison resistance; poisonous to eat" },
    { "cobra", "may confer poison resistance; poisonous to eat" },
    { "troll", "none" },
    { "ice troll", "may confer cold resistance" },
    { "rock troll", "none" },
    { "water troll", "none" },
    { "olog-hai", "none" },
    { "umber hulk", "none" },
    { "vampire", "poisonous to eat" },
    { "vampire lord", "poisonous to eat" },
    { "vlad the impaler", "poisonous to eat" },
    { "barrow wight", "none" },
    { "wraith", "grants an experience level" },
    { "nazgul", "none" },
    { "xorn", "none" },
    { "monkey", "none" },
    { "ape", "none" },
    { "owlbear", "none" },
    { "yeti", "may confer cold resistance" },
    { "carnivorous ape", "none" },
    { "sasquatch", "none" },
    { "kobold zombie", "poisonous to eat" },
    { "gnome zombie", "poisonous to eat; counts as cannibalism for Gnomish characters" },
    { "orc zombie", "poisonous to eat; counts as cannibalism for Orcish characters" },
    { "dwarf zombie", "poisonous to eat; counts as cannibalism for Dwarven characters" },
    { "elf zombie", "counts as cannibalism for Elven characters" },
    { "human zombie", "none" },
    { "ettin zombie", "none" },
    { "ghoul", "poisonous to eat" },
    { "giant zombie", "may confer strength gain" },
    { "skeleton", "none" },
    { "straw golem", "none" },
    { "paper golem", "none" },
    { "rope golem", "none" },
    { "gold golem", "none" },
    { "leather golem", "none" },
    { "wood golem", "none" },
    { "flesh golem", "may confer fire resistance, cold resistance, sleep resistance, shock resistance, poison resistance" },
    { "clay golem", "none" },
    { "stone golem", "none" },
    { "glass golem", "none" },
    { "iron golem", "poisonous to eat" },
    { "human", "counts as cannibalism for Human characters" },
    { "wererat", "risk of lycanthropy; poisonous to eat; counts as cannibalism for Human characters" },
    { "werejackal", "risk of lycanthropy; poisonous to eat; counts as cannibalism for Human characters" },
    { "werewolf", "risk of lycanthropy; poisonous to eat; counts as cannibalism for Human characters" },
    { "elf", "may confer sleep resistance; counts as cannibalism for Elven characters" },
    { "woodland-elf", "may confer sleep resistance; counts as cannibalism for Elven characters" },
    { "green-elf", "may confer sleep resistance; counts as cannibalism for Elven characters" },
    { "grey-elf", "may confer sleep resistance; counts as cannibalism for Elven characters" },
    { "elf-lord", "may confer sleep resistance; counts as cannibalism for Elven characters" },
    { "elvenking", "may confer sleep resistance; counts as cannibalism for Elven characters" },
    { "doppelganger", "counts as cannibalism for Human characters" },
    { "shopkeeper", "counts as cannibalism for Human characters" },
    { "guard", "counts as cannibalism for Human characters" },
    { "prisoner", "counts as cannibalism for Human characters" },
    { "oracle", "counts as cannibalism for Human characters" },
    { "aligned priest", "counts as cannibalism for Human characters" },
    { "high priest", "counts as cannibalism for Human characters" },
    { "soldier", "counts as cannibalism for Human characters" },
    { "sergeant", "counts as cannibalism for Human characters" },
    { "nurse", "may confer poison resistance; fully heals you and cures blindness; counts as cannibalism for Human characters" },
    { "lieutenant", "counts as cannibalism for Human characters" },
    { "captain", "counts as cannibalism for Human characters" },
    { "watchman", "counts as cannibalism for Human characters" },
    { "watch captain", "counts as cannibalism for Human characters" },
    { "medusa", "instant stoning unless stoning-resistant; may confer poison resistance; poisonous to eat" },
    { "wizard of yendor", "may confer fire resistance, poison resistance; may confer teleportitis; may confer teleport control; counts as cannibalism for Human characters" },
    { "croesus", "counts as cannibalism for Human characters" },
    { "ghost", "none" },
    { "shade", "none" },
    { "water demon", "poisonous to eat" },
    { "succubus", "poisonous to eat" },
    { "horned devil", "poisonous to eat" },
    { "incubus", "poisonous to eat" },
    { "erinys", "poisonous to eat" },
    { "barbed devil", "poisonous to eat" },
    { "marilith", "poisonous to eat" },
    { "vrock", "poisonous to eat" },
    { "hezrou", "poisonous to eat" },
    { "bone devil", "poisonous to eat" },
    { "ice devil", "poisonous to eat" },
    { "nalfeshnee", "poisonous to eat" },
    { "pit fiend", "poisonous to eat" },
    { "sandestin", "none" },
    { "balrog", "poisonous to eat" },
    { "juiblex", "poisonous to eat; acidic to eat; cures stoning if eaten while petrifying" },
    { "yeenoghu", "poisonous to eat" },
    { "orcus", "poisonous to eat" },
    { "geryon", "poisonous to eat" },
    { "dispater", "poisonous to eat" },
    { "baalzebub", "poisonous to eat; causes hallucination" },
    { "asmodeus", "poisonous to eat" },
    { "demogorgon", "poisonous to eat" },
    { "death", "instant death (do not eat); may confer teleport control; never rots" },
    { "pestilence", "instant death (do not eat); may confer teleport control; never rots" },
    { "famine", "instant death (do not eat); may confer teleport control; never rots" },
    { "mail daemon", "poisonous to eat" },
    { "djinni", "poisonous to eat" },
    { "jellyfish", "may confer poison resistance; poisonous to eat" },
    { "piranha", "none" },
    { "shark", "none" },
    { "giant eel", "none" },
    { "electric eel", "may confer shock resistance" },
    { "kraken", "none" },
    { "newt", "may restore a small amount of energy" },
    { "gecko", "none" },
    { "iguana", "none" },
    { "baby crocodile", "none" },
    { "lizard", "cures stoning if eaten while petrifying; never rots; cures stunning and confusion" },
    { "chameleon", "none" },
    { "crocodile", "none" },
    { "salamander", "may confer fire resistance; poisonous to eat" },
    { "long worm tail", "none" },
    { "archeologist", "counts as cannibalism for Human characters" },
    { "barbarian", "counts as cannibalism for Human characters" },
    { "caveman", "counts as cannibalism for Human characters" },
    { "cavewoman", "counts as cannibalism for Human characters" },
    { "healer", "counts as cannibalism for Human characters" },
    { "knight", "counts as cannibalism for Human characters" },
    { "monk", "counts as cannibalism for Human characters" },
    { "priest", "counts as cannibalism for Human characters" },
    { "priestess", "counts as cannibalism for Human characters" },
    { "ranger", "counts as cannibalism for Human characters" },
    { "rogue", "counts as cannibalism for Human characters" },
    { "samurai", "counts as cannibalism for Human characters" },
    { "tourist", "counts as cannibalism for Human characters" },
    { "valkyrie", "counts as cannibalism for Human characters" },
    { "wizard", "counts as cannibalism for Human characters" },
    { "lord carnarvon", "counts as cannibalism for Human characters" },
    { "pelias", "counts as cannibalism for Human characters" },
    { "shaman karnov", "counts as cannibalism for Human characters" },
    { "hippocrates", "counts as cannibalism for Human characters" },
    { "king arthur", "counts as cannibalism for Human characters" },
    { "grand master", "counts as cannibalism for Human characters" },
    { "arch priest", "counts as cannibalism for Human characters" },
    { "orion", "counts as cannibalism for Human characters" },
    { "master of thieves", "counts as cannibalism for Human characters" },
    { "lord sato", "counts as cannibalism for Human characters" },
    { "twoflower", "counts as cannibalism for Human characters" },
    { "norn", "counts as cannibalism for Human characters" },
    { "neferet the green", "counts as cannibalism for Human characters" },
    { "minion of huhetotl", "poisonous to eat" },
    { "thoth amon", "counts as cannibalism for Human characters" },
    { "chromatic dragon", "may confer fire resistance, cold resistance, sleep resistance, disintegration resistance, shock resistance, poison resistance; poisonous to eat" },
    { "cyclops", "may confer strength gain" },
    { "ixoth", "may confer fire resistance" },
    { "master kaen", "may confer poison resistance; counts as cannibalism for Human characters" },
    { "nalzok", "poisonous to eat" },
    { "scorpius", "may confer poison resistance; poisonous to eat" },
    { "master assassin", "counts as cannibalism for Human characters" },
    { "ashikaga takauji", "counts as cannibalism for Human characters" },
    { "lord surtur", "may confer fire resistance; may confer strength gain" },
    { "dark one", "counts as cannibalism for Human characters" },
    { "student", "counts as cannibalism for Human characters" },
    { "chieftain", "counts as cannibalism for Human characters" },
    { "neanderthal", "counts as cannibalism for Human characters" },
    { "attendant", "counts as cannibalism for Human characters" },
    { "page", "counts as cannibalism for Human characters" },
    { "abbot", "counts as cannibalism for Human characters; causes hallucination" },
    { "acolyte", "counts as cannibalism for Human characters" },
    { "hunter", "counts as cannibalism for Human characters" },
    { "thug", "counts as cannibalism for Human characters" },
    { "ninja", "counts as cannibalism for Human characters" },
    { "roshi", "counts as cannibalism for Human characters" },
    { "guide", "counts as cannibalism for Human characters" },
    { "warrior", "counts as cannibalism for Human characters" },
    { "apprentice", "counts as cannibalism for Human characters" },
    { (const char *) 0, (const char *) 0 } /* sentinel */
};

/* 382 entries */

#endif /* MCONVEYS_H */
